//! Signing payloads for Soroban authorization entries.
//!
//! A `SorobanAuthorizationEntry` with address credentials is signed over
//! `SHA-256(XDR(HashIDPreimage::SorobanAuthorization))`. Every on-chain check
//! Sigil performs depends on these bytes being exactly right, so the layout is
//! pinned against a fixture generated by the JavaScript SDK. See
//! `fixtures/auth_preimage_v1.json` and the tests below.

use sha2::{Digest, Sha256};
use stellar_xdr::curr::{
    Hash, HashIdPreimage, HashIdPreimageSorobanAuthorization, Limits, SorobanAuthorizedInvocation,
    WriteXdr,
};

pub const TESTNET_PASSPHRASE: &str = "Test SDF Network ; September 2015";
pub const PUBNET_PASSPHRASE: &str = "Public Global Stellar Network ; September 2015";

#[derive(Debug)]
pub enum Error {
    Xdr(stellar_xdr::curr::Error),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Xdr(e) => write!(f, "xdr: {e}"),
        }
    }
}

impl std::error::Error for Error {}

impl From<stellar_xdr::curr::Error> for Error {
    fn from(e: stellar_xdr::curr::Error) -> Self {
        Error::Xdr(e)
    }
}

/// The network id is the SHA-256 of the network passphrase.
pub fn network_id(passphrase: &str) -> Hash {
    Hash(Sha256::digest(passphrase.as_bytes()).into())
}

/// Builds the preimage a signer must sign for an address-credentials auth entry.
pub fn authorization_preimage(
    network_id: Hash,
    nonce: i64,
    signature_expiration_ledger: u32,
    invocation: SorobanAuthorizedInvocation,
) -> HashIdPreimage {
    HashIdPreimage::SorobanAuthorization(HashIdPreimageSorobanAuthorization {
        network_id,
        nonce,
        signature_expiration_ledger,
        invocation,
    })
}

/// XDR encoding of the preimage.
pub fn preimage_bytes(preimage: &HashIdPreimage) -> Result<Vec<u8>, Error> {
    Ok(preimage.to_xdr(Limits::none())?)
}

/// The 32 bytes an authorizing signer actually signs.
pub fn signature_payload(preimage: &HashIdPreimage) -> Result<[u8; 32], Error> {
    Ok(Sha256::digest(preimage_bytes(preimage)?).into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use stellar_xdr::curr::ReadXdr;

    #[derive(serde::Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct Fixture {
        network_passphrase: String,
        network_id_hex: String,
        nonce: String,
        signature_expiration_ledger: u32,
        invocation_xdr_base64: String,
        preimage_xdr_base64: String,
        preimage_sha256_hex: String,
    }

    fn fixture() -> Fixture {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../fixtures/auth_preimage_v1.json"
        );
        serde_json::from_str(&std::fs::read_to_string(path).expect("fixture readable"))
            .expect("fixture parses")
    }

    #[test]
    fn network_id_matches_js_sdk() {
        let f = fixture();
        assert_eq!(
            hex::encode(network_id(&f.network_passphrase).0),
            f.network_id_hex
        );
    }

    #[test]
    fn preimage_encoding_matches_js_sdk() {
        let f = fixture();
        let invocation =
            SorobanAuthorizedInvocation::from_xdr_base64(&f.invocation_xdr_base64, Limits::none())
                .expect("invocation decodes");

        let preimage = authorization_preimage(
            network_id(&f.network_passphrase),
            f.nonce.parse().expect("nonce parses"),
            f.signature_expiration_ledger,
            invocation,
        );

        let encoded = preimage.to_xdr_base64(Limits::none()).expect("encodes");
        assert_eq!(
            encoded, f.preimage_xdr_base64,
            "preimage XDR diverged from the JS SDK"
        );

        let payload = signature_payload(&preimage).expect("hashes");
        assert_eq!(hex::encode(payload), f.preimage_sha256_hex);
    }
}
